close all;
clear all;
clc;
x=[0 1 1 0;1 0 0 1;1 0 0 1;0 1 1 0];
B=[0 1 0;1 1 1;0 1 0];
Erx=imerode(x,B);
Erf=imerode(Erx,B);
disp('Idempotency1 LHS');
disp(Erf);
Erx1=imerode(x,B);
disp('Idempotency1 RHS');
disp(Erx1);
Dix1=imdilate(x,B);
Dix=imdilate(Dix1,B);
disp('Idempotency2 LHS');
disp(Dix);
Dix2=imdilate(x,B);
disp('Idempotency2 RHS');
disp(Dix2);
