X=[0 1 1 0;1 0 0 1;1 0 0 1;0 1 1 0];
Y=[1 1 1 1 0 0;0 1 1 1 1 0;0 1 1 1 1 0;0 1 1 1 0 0;0 1 0 1 0 0; 1 1 0 0 1 1];
B=[0 1 0;1 1 1;0 1 0];
Erx=imerode(X,B);
ErX=imerode(Y,B);
Dix=imdilate(X,B);
DiX=imdilate(Y,B);
Opx=imopen(X,B);
OpX=imopen(Y,B);
Clx=imclose(X,B);
ClX=imclose(Y,B);
disp('Eroded image of X');
disp(Erx);
disp('Eroded image of Y');
disp(ErX);
disp('Dilated image of X');
disp(Dix);
disp('Dilated image of Y');
disp(DiX);
disp('Opened image of X');
disp(Opx);
disp('Opened image of Y');
disp(OpX);
disp('closed image of X');
disp(Clx);
disp('closed image of Y');
disp(ClX);
